
const SET_NAME = "SET_NAME",CART_COUNT_INCREMENT = "CART_COUNT_INCREMENT",CART_COUNT_DECREMENT = "CART_COUNT_DECREMENT",
FETCH_PRODUCTS_CATEGORY = "FETCH_PRODUCTS_CATEGORY",SET_PRODUCTS_CATEGORY = "SET_PRODUCTS_CATEGORY";
;

export {
    SET_NAME,
    CART_COUNT_INCREMENT,
    CART_COUNT_DECREMENT,
    FETCH_PRODUCTS_CATEGORY,
    SET_PRODUCTS_CATEGORY
}

